[font]
size = 14.0

[cursor]
unfocused_hollow = false

[window.padding]
x = 0
y = 0

[cursor.style]
blinking = "On"
shape = "Block"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.8
blur = true
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[colors.bright]
black = "#565f89"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.normal]
black = "#24283b"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"

